/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(platform(project(":version-platform")))
    api(project(":miya-common"))
    api(libs.com.aliyun.oss.aliyun.sdk.oss)
    api(libs.com.aliyun.dysmsapi20170525)

    annotationProcessor(libs.org.projectlombok.lombok)
}

description = "miya-sms-service"
