/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(platform(project(":version-platform")))
    annotationProcessor(platform(project(":version-platform")))

    api(project(":miya-common"))
    // 处理启动解析xml报错
    implementation("org.dom4j:dom4j:2.1.4")
    api("com.aliyun.oss:aliyun-sdk-oss:3.16.1") {
        exclude(group = "org.dom4j", module = "dom4j")
    }
    // implementation 'pull-parser:pull-parser:2'
    api(libs.com.aliyun.dysmsapi20170525)

    annotationProcessor("org.projectlombok:lombok")
}

description = "miya-sms-service"
