version: "3.8"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - db-data:/var/lib/mysql
      - db-config:/etc/mysql/conf.d
    networks:
      - db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
networks:
  db:
    external: true
volumes:
  db-data:
  db-config:
